package Interfaces;

import Login.Start;
import com.toedter.calendar.JDateChooser;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.text.DateFormat;
import java.time.LocalDate;
import java.util.Calendar;
import java.util.Scanner;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class ClientInterface extends javax.swing.JFrame {

    File cliente;
    File cita;
    File agenda;

    public ClientInterface() {
        initComponents();
        centreWindow();
        TablaSolicitud();
    }

    private void centreWindow() {
        Dimension dimension = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (int) ((dimension.getWidth() - this.getWidth()) / 2);
        int y = (int) ((dimension.getHeight() - this.getHeight()) / 2);
        this.setLocation(x, y - 25);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SolicitudCita = new javax.swing.JFrame();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        SolicitarCita = new javax.swing.JButton();
        ModificarCita = new javax.swing.JFrame();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        buscar = new javax.swing.JTextField();
        cancelarCita = new javax.swing.JButton();
        guardarCambios = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        content = new javax.swing.JPanel();
        reg_title = new javax.swing.JLabel();
        requestQuoteButton = new javax.swing.JButton();
        modifyQuoteButton = new javax.swing.JButton();
        registryButton = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        main_tittle = new javax.swing.JPanel();
        tittle = new javax.swing.JLabel();
        showName = new javax.swing.JLabel();
        color = new javax.swing.JTextField();
        raza = new javax.swing.JTextField();
        cedula = new javax.swing.JTextField();
        nombrePerro = new javax.swing.JTextField();
        fecha = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        SolicitudCita.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        SolicitudCita.setTitle("Solicitud de Citas");
        SolicitudCita.setResizable(false);
        SolicitudCita.setSize(new java.awt.Dimension(460, 270));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Tabla de Servicios");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Servicio", "Costo", "Tiempo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTable1MouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
        }

        SolicitarCita.setText("Solicitar Cita");
        SolicitarCita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SolicitarCitaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SolicitudCitaLayout = new javax.swing.GroupLayout(SolicitudCita.getContentPane());
        SolicitudCita.getContentPane().setLayout(SolicitudCitaLayout);
        SolicitudCitaLayout.setHorizontalGroup(
            SolicitudCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SolicitudCitaLayout.createSequentialGroup()
                .addGap(0, 33, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
            .addGroup(SolicitudCitaLayout.createSequentialGroup()
                .addGroup(SolicitudCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SolicitudCitaLayout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(jLabel9))
                    .addGroup(SolicitudCitaLayout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(SolicitarCita, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        SolicitudCitaLayout.setVerticalGroup(
            SolicitudCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SolicitudCitaLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SolicitarCita)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ModificarCita.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        ModificarCita.setTitle("Modificación/Cancelacion de Citas");
        ModificarCita.setResizable(false);
        ModificarCita.setSize(new java.awt.Dimension(650, 350));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Tabla de Cancelación/Modificacion de Citas");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Fecha Consulta", "Cedula del Dueño", "Nombre del Perro", "Servicio", "Hora", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(0).setResizable(false);
            jTable2.getColumnModel().getColumn(1).setResizable(false);
            jTable2.getColumnModel().getColumn(2).setResizable(false);
            jTable2.getColumnModel().getColumn(3).setResizable(false);
            jTable2.getColumnModel().getColumn(4).setResizable(false);
            jTable2.getColumnModel().getColumn(5).setResizable(false);
        }

        jLabel12.setText("Cedula:");

        buscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                buscarKeyReleased(evt);
            }
        });

        cancelarCita.setText("Cancelar Cita");
        cancelarCita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarCitaActionPerformed(evt);
            }
        });

        guardarCambios.setText("Guardar Cambios");
        guardarCambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarCambiosActionPerformed(evt);
            }
        });

        jButton1.setText("Cambiar Servicio");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Para cambiar un servicio, primero debe seleccionar una cita en la tabla.");

        jLabel8.setText("En esta tabla se mostraran las citas que ya tienen un dia y hora asignadas.");

        javax.swing.GroupLayout ModificarCitaLayout = new javax.swing.GroupLayout(ModificarCita.getContentPane());
        ModificarCita.getContentPane().setLayout(ModificarCitaLayout);
        ModificarCitaLayout.setHorizontalGroup(
            ModificarCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ModificarCitaLayout.createSequentialGroup()
                .addGroup(ModificarCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ModificarCitaLayout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(jLabel11))
                    .addGroup(ModificarCitaLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ModificarCitaLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cancelarCita)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(guardarCambios)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addGroup(ModificarCitaLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(ModificarCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel2))))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        ModificarCitaLayout.setVerticalGroup(
            ModificarCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ModificarCitaLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ModificarCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelarCita)
                    .addComponent(guardarCambios)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registro de Clientes");
        setResizable(false);

        content.setBackground(new java.awt.Color(255, 255, 255));
        content.setPreferredSize(new java.awt.Dimension(650, 440));
        content.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        reg_title.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        reg_title.setForeground(new java.awt.Color(255, 102, 0));
        reg_title.setText("Registro de clientes");
        content.add(reg_title, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 180, -1));

        requestQuoteButton.setBackground(new java.awt.Color(8, 156, 255));
        requestQuoteButton.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        requestQuoteButton.setText("Solicitar cita");
        requestQuoteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestQuoteButtonActionPerformed(evt);
            }
        });
        content.add(requestQuoteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 230, 160, 30));

        modifyQuoteButton.setBackground(new java.awt.Color(8, 156, 255));
        modifyQuoteButton.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        modifyQuoteButton.setText("Modificar cita");
        modifyQuoteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyQuoteButtonActionPerformed(evt);
            }
        });
        content.add(modifyQuoteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 190, 160, 30));

        registryButton.setBackground(new java.awt.Color(8, 156, 255));
        registryButton.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        registryButton.setText("Registrar");
        registryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registryButtonActionPerformed(evt);
            }
        });
        content.add(registryButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 340, 110, 60));

        jButton3.setBackground(new java.awt.Color(8, 156, 255));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setText("Volver");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        content.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        main_tittle.setBackground(new java.awt.Color(8, 156, 255));

        tittle.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        tittle.setText("BIENVENIDO");
        main_tittle.add(tittle);

        showName.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        main_tittle.add(showName);

        content.add(main_tittle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 60));
        content.add(color, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 150, 110, -1));
        content.add(raza, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 120, 110, -1));
        content.add(cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 110, -1));
        content.add(nombrePerro, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 110, -1));
        content.add(fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, 90, -1));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Cedula del Dueño:");
        content.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 140, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nombre del perro:");
        content.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Fecha de Nacimiento:");
        content.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Raza:");
        content.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 120, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Color:");
        content.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 150, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/data/Imagenes/inicio.jpg"))); // NOI18N
        content.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, 60, 620, 380));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(content, javax.swing.GroupLayout.PREFERRED_SIZE, 617, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registryButtonActionPerformed
        String data[] = {nombrePerro.getText(), raza.getText(), color.getText()};
        if (Esnumero(cedula.getText()) && NoVacia(data) && IngresoFecha(fecha)) {
            //Datos del JDateChooser
            int dia = fecha.getCalendar().get(Calendar.DAY_OF_MONTH);
            int mes = fecha.getCalendar().get(Calendar.MONTH) + 1;
            int año = fecha.getCalendar().get(Calendar.YEAR);
            //Datos de la fecha actual
            int diaActual = LocalDate.now().getDayOfMonth();
            int mesActual = LocalDate.now().getMonthValue();
            int añoActual = LocalDate.now().getYear();
            if (ValidarFecha(dia, diaActual, mes, mesActual, año, añoActual)) {
                //Datos para crear el archivo de Clientes
                String sDir = "C:\\user"; // direccion
                File f = new File(sDir); // instancia de la carpeta
                String ruta = "C:\\user"; // ruta para el archivo
                String fileName = "Clientes.txt"; // nombre
                cliente = new File(ruta, fileName); // instancia el archivo

                if (!cliente.exists()) {//Reviso que el archivo no exista
                    try {
                        //Verifica si el archivo existe o no
                        f.mkdir();
                        cliente.createNewFile();//Creo el archivo
                    } catch (IOException ex) {
                        JOptionPane.showMessageDialog(content, "Error", "El archivo no se encontró", JOptionPane.ERROR_MESSAGE);
                    }

                }

                //Se saca la información de los TextFields
                String ced = cedula.getText();
                String nombre = nombrePerro.getText();
                String razaPerro = raza.getText();
                String colorPerro = color.getText();
                String date = DateFormat.getDateInstance().format(fecha.getDate());

                //Se escribe la informacion en el archivo
                try (FileWriter fw = new FileWriter(cliente.getAbsolutePath(), true)) {
                    BufferedWriter bw = new BufferedWriter(fw);//Creo el buffered
                    if (!CitaRepetida(cliente, ced, nombre)) {
                        bw.write(ced + "," + nombre + "," + razaPerro + "," + colorPerro + "," + date);
                        bw.newLine();
                    }
                    bw.flush();
                    bw.close();
                    fw.close();
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(content, "Error inesperado", "Error", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(content, "Error en la fecha de nacimiento", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(content, "Por favor, debe ingresar todos los datos", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_registryButtonActionPerformed

    private void requestQuoteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestQuoteButtonActionPerformed
        ModificarCita.dispose();
        SolicitudCita.setVisible(true);
    }//GEN-LAST:event_requestQuoteButtonActionPerformed

    private void modifyQuoteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyQuoteButtonActionPerformed
        SolicitudCita.dispose();
        ModificarCita.setVisible(true);
    }//GEN-LAST:event_modifyQuoteButtonActionPerformed

    private void guardarCambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarCambiosActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
        save(model);//Se guarda la informacion en el archivo
    }//GEN-LAST:event_guardarCambiosActionPerformed

    private void cancelarCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarCitaActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
        int selected = (int) jTable2.getSelectedRow();
        if (selected > -1) {
            model.setValueAt("Cancelada", selected, 5);
        } else {
            JOptionPane.showMessageDialog(content, "Debe seleccionar una cita", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_cancelarCitaActionPerformed

    private void buscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buscarKeyReleased
        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
        model.setRowCount(0);//Borro los registros
        if (Esnumero(buscar.getText()) && !buscar.getText().isEmpty()) {//Reviso que ingrese un numero o que la cadena no este vacia
            File archivo = new File("C:\\user\\AgendaAdmin.txt");
            if (archivo.exists()) {
                try (Scanner sc = new Scanner(archivo)) {//Abro el archivo
                    while (sc.hasNextLine()) {//mientras halla una siguiente linea
                        String linea = sc.nextLine();
                        String data[] = linea.split(",");
                        String date = data[0];
                        String ced = data[1];
                        String nombre = data[2];
                        String servicio = data[3];
                        String hora = data[4];
                        String estado = data[5];
                        if (ced.equals(buscar.getText())) {//si encuentro coincidencias, muestra los datos en la tabla
                            model.addRow(new Object[]{date, ced, nombre, servicio, hora, estado});//Muestro los datos de esa cedula
                        }
                    }
                    sc.close();
                } catch (FileNotFoundException ex) {
                    JOptionPane.showMessageDialog(content, "Archivo no encontrado", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        } else {
            model.setRowCount(0);//Se borran otra vez los registros
        }
    }//GEN-LAST:event_buscarKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (jTable2.getSelectedRow() > -1) {
            SolicitarCita.setEnabled(false);
            SolicitarCita.setVisible(false);
            SolicitudCita.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(content, "Debe seleccionar almenos 1 cita", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void SolicitarCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SolicitarCitaActionPerformed
        int selected = jTable1.getSelectedRow();
        if (selected > -1) {
            String data[] = {nombrePerro.getText(), raza.getText(), color.getText()};
            if (Esnumero(cedula.getText()) && NoVacia(data) && IngresoFecha(fecha)) {
                if (ClienteExiste(cedula.getText(), nombrePerro.getText())) {
                    //Datos del JDateChooser
                    int dia = fecha.getCalendar().get(Calendar.DAY_OF_MONTH);
                    int mes = fecha.getCalendar().get(Calendar.MONTH) + 1;
                    int año = fecha.getCalendar().get(Calendar.YEAR);
                    //Datos de la fecha actual
                    int diaActual = LocalDate.now().getDayOfMonth();
                    int mesActual = LocalDate.now().getMonthValue();
                    int añoActual = LocalDate.now().getYear();

                    if (ValidarFecha(dia, diaActual, mes, mesActual, año, añoActual)) {
                        //Se crean las variables para el archivo agenda
                        String direccion = "C:\\user";
                        File f = new File(direccion);
                        String dir = "C:\\user";
                        String nameFile = "Citas.txt";
                        cita = new File(dir, nameFile);

                        //Se revisa que no exista el archivo agenda
                        if (!cita.exists()) {
                            try {
                                f.mkdir();
                                cita.createNewFile();
                            } catch (IOException ex) {
                                JOptionPane.showMessageDialog(content, "Error inesperado", "Error", JOptionPane.ERROR_MESSAGE);
                            }
                        }

                        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                        String serv = (String) model.getValueAt(selected, 0);//Recupero el sevicio que selecciono
                        String ced = cedula.getText();
                        String nombre = nombrePerro.getText();
                        String estado = "Solicitada";

                        try (FileWriter fw = new FileWriter(cita.getAbsolutePath(), true)) {
                            BufferedWriter bw = new BufferedWriter(fw);
                            if (!CitaRepetida(cita, ced, nombre)) {
                                bw.write(ced + "," + nombre + "," + serv + "," + estado);
                                bw.newLine();
                            }
                            bw.flush();
                            bw.close();
                            fw.close();
                        } catch (Exception e) {
                            JOptionPane.showMessageDialog(content, "Error inesperado", "Error", JOptionPane.ERROR_MESSAGE);
                        }
                    } else {
                        JOptionPane.showMessageDialog(content, "Error en la fecha de nacimiento", "Error", JOptionPane.ERROR_MESSAGE);
                    }
                } else {
                    JOptionPane.showMessageDialog(content, "Debe registrarse primero", "Error", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(content, "Por favor ingrese todos los datos", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(content, "Debe seleccionar un servicio", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_SolicitarCitaActionPerformed

    private void jTable1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseReleased
        if (!SolicitarCita.isEnabled()) {
            DefaultTableModel model = (DefaultTableModel) jTable2.getModel();//Tabla de cancelacion de citas
            DefaultTableModel model2 = (DefaultTableModel) jTable1.getModel();//Tabla de servicios
            int selectedServicios = jTable1.getSelectedRow();//Servicio seleccionado
            int selectedCitas = jTable2.getSelectedRow();//Cita seleccionada
            if (jTable1.getSelectedRow() > -1) {
                model.setValueAt(model2.getValueAt(selectedServicios, 0), selectedCitas, 3);//Cambio el servicio de la tabla
            }
        }
    }//GEN-LAST:event_jTable1MouseReleased

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.dispose();
        new Start().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    //Se valida que la cedula que ingresan sea numerico
    private boolean Esnumero(String cadena) {
        try {
            Integer.parseInt(cadena);
            return true;
        } catch (NumberFormatException e) {
            return false;
        }
    }

    //Se valida que todos los datos hallan sido ingresados
    private boolean NoVacia(String[] cadena) {
        for (String cad : cadena) {
            if (cad.isEmpty()) {
                return false;
            }
        }
        return true;
    }

    //Función para colocar los datos en la tabla de solicitid de citas
    private void TablaSolicitud() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Consulta", 60000, "1 hora"});
        model.addRow(new Object[]{"Control", 10000, "1/2 hora"});
        model.addRow(new Object[]{"Desparasitación", 40000, "1/2 hora"});
        model.addRow(new Object[]{"Vacunación", 35000, "1/2 hora"});
        model.addRow(new Object[]{"Guarderia", 35000, "Solo por dia"});
        model.addRow(new Object[]{"Radiologia", 100000, "1 hora"});
        model.addRow(new Object[]{"Baño", 25000, "2 horas"});
    }

    private boolean CitaRepetida(File archivo, String cedula, String nombre) {
        if (archivo.exists()) {
            try (Scanner sc = new Scanner(archivo)) {
                while (sc.hasNextLine()) {
                    String linea = sc.nextLine();
                    String data[] = linea.split(",");
                    if (data[0].equals(cedula) && data[1].equals(nombre)) {
                        sc.close();
                        return true;
                    }
                }
                sc.close();
                return false;
            } catch (FileNotFoundException ex) {
                return false;
            }
        }
        return false;
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame ModificarCita;
    private javax.swing.JButton SolicitarCita;
    private javax.swing.JFrame SolicitudCita;
    private javax.swing.JTextField buscar;
    private javax.swing.JButton cancelarCita;
    private javax.swing.JTextField cedula;
    private javax.swing.JTextField color;
    private javax.swing.JPanel content;
    private com.toedter.calendar.JDateChooser fecha;
    private javax.swing.JButton guardarCambios;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JPanel main_tittle;
    private javax.swing.JButton modifyQuoteButton;
    private javax.swing.JTextField nombrePerro;
    private javax.swing.JTextField raza;
    private javax.swing.JLabel reg_title;
    private javax.swing.JButton registryButton;
    private javax.swing.JButton requestQuoteButton;
    private javax.swing.JLabel showName;
    private javax.swing.JLabel tittle;
    // End of variables declaration//GEN-END:variables

    //Actualizo los datos
    private void save(DefaultTableModel model) {
        String direccion = "C:\\user";
        File f = new File(direccion);
        String dir = "C:\\user";
        String nameFile = "Cambios.txt";
        File archivo = new File(dir, nameFile);
        agenda = new File("C:\\user\\AgendaAdmin.txt");

        if (!archivo.exists()) {
            f.mkdir();
            try {
                archivo.createNewFile();
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(content, "Error inesperado", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }

        if (agenda.exists()) {
            try (FileWriter fw = new FileWriter(archivo.getAbsoluteFile())) {
                BufferedWriter bw = new BufferedWriter(fw);
                Scanner sc = new Scanner(agenda);
                while (sc.hasNextLine()) {
                    String linea = sc.nextLine();
                    String data[] = linea.split(",");
                    String date = data[0];
                    String ced = data[1];
                    String nombre = data[2];
                    String servicio = data[3];
                    String hora = data[4];
                    String estado = data[5];
                    for (int i = 0; i < model.getRowCount(); i++) {
                        if (model.getValueAt(i, 1).equals(ced) && model.getValueAt(i, 2).equals(nombre)) {
                            ced = (String) model.getValueAt(i, 0);
                            nombre = (String) model.getValueAt(i, 1);
                            servicio = (String) model.getValueAt(i, 2);
                            date = (String) model.getValueAt(i, 3);
                            hora = (String) model.getValueAt(i, 4);
                            estado = (String) model.getValueAt(i, 5);
                        }
                    }
                    if (servicio.equals("Baño") || servicio.equals("Guarderia")) {
                        hora = "no necesita";
                    }
                    bw.write(date + "," + ced + "," + nombre + "," + servicio + "," + hora + "," + estado);
                    bw.newLine();
                }
                bw.flush();
                bw.close();
                fw.close();
                sc.close();
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(content, "Error inesperado", "Error", JOptionPane.ERROR_MESSAGE);
            }

            try (FileWriter fw = new FileWriter(agenda.getAbsoluteFile())) {
                BufferedWriter bw = new BufferedWriter(fw);
                Scanner sc = new Scanner(archivo);
                while (sc.hasNextLine()) {
                    String linea = sc.nextLine();
                    String data[] = linea.split(",");
                    bw.write(data[0] + "," + data[1] + "," + data[2] + "," + data[3] + "," + data[4] + "," + data[5]);
                    bw.newLine();
                }
                bw.flush();
                bw.close();
                fw.close();
                sc.close();
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(content, "Error inesperado", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        archivo.delete();
    }

    //Valido la fecha del JDateChooser
    private boolean ValidarFecha(int dia, int diaActual, int mes, int mesActual, int año, int añoActual) {
        if (año < añoActual) {//Si el año es menor, la fecha es valida
            return true;
        } else if (año == añoActual && mes < mesActual) {//Si el año es igual y el mes es menor, la fecha es valida
            return true;
        } else if (año == añoActual && mes == mesActual && dia <= diaActual) {//Si tanto el año y el mes son iguales y el dia es menor o igual al actual, la fecha es valida
            return true;
        }
        return false;
    }

    private boolean ClienteExiste(String cedula, String nombre) {
        cliente = new File("C:\\user\\Clientes.txt");
        if (cliente.exists()) {
            try (Scanner sc = new Scanner(cliente)) {
                while (sc.hasNextLine()) {
                    String linea = sc.nextLine();
                    String data[] = linea.split(",");
                    String ced = data[0];
                    String nom = data[1];
                    if (ced.equals(cedula) && nom.equals(nombre)) {
                        sc.close();
                        return true;
                    }
                }
                sc.close();
            } catch (FileNotFoundException e) {
            }
        }
        return false;
    }

    private boolean IngresoFecha(JDateChooser date){
        try{
            String g = String.valueOf(date.getCalendar().get(Calendar.DATE));
            return true;
        }catch(Exception e){
            return false;
        }
    }
    
}
