package Login;

import Interfaces.ClientInterface;
import java.awt.Dimension;
import java.awt.Toolkit;

public class Start extends javax.swing.JFrame {

    public Start() {
        initComponents();
        centreWindow();
    }

    private void centreWindow() {
        Dimension dimension = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (int) ((dimension.getWidth() - this.getWidth()) / 2);
        int y = (int) ((dimension.getHeight() - this.getHeight()) / 2);
        this.setLocation(x, y - 25);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cardCOntent = new javax.swing.JPanel();
        clientButton = new javax.swing.JButton();
        vetButton = new javax.swing.JButton();
        adminButton = new javax.swing.JButton();
        vetTitle = new javax.swing.JLabel();
        imgBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Veterinaria PerrosPET");
        setResizable(false);

        cardCOntent.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        clientButton.setBackground(new java.awt.Color(153, 255, 255));
        clientButton.setText("Cliente");
        clientButton.setFocusable(false);
        clientButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientButtonActionPerformed(evt);
            }
        });
        cardCOntent.add(clientButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 160, 50));

        vetButton.setBackground(new java.awt.Color(153, 255, 255));
        vetButton.setText("Veterinario");
        vetButton.setFocusable(false);
        vetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vetButtonActionPerformed(evt);
            }
        });
        cardCOntent.add(vetButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 160, 50));

        adminButton.setBackground(new java.awt.Color(153, 255, 255));
        adminButton.setText("Administrador");
        adminButton.setFocusable(false);
        adminButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminButtonActionPerformed(evt);
            }
        });
        cardCOntent.add(adminButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 160, 50));

        vetTitle.setFont(new java.awt.Font("Castellar", 1, 18)); // NOI18N
        vetTitle.setForeground(new java.awt.Color(255, 102, 51));
        vetTitle.setText("veterinaria Perros PET");
        cardCOntent.add(vetTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, -1, -1));

        imgBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/data/Imagenes/Clientes.jpg"))); // NOI18N
        cardCOntent.add(imgBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 390));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cardCOntent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cardCOntent, javax.swing.GroupLayout.PREFERRED_SIZE, 389, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clientButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientButtonActionPerformed
        new ClientInterface().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_clientButtonActionPerformed

    private void vetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vetButtonActionPerformed
        new LoginInterface("Veterinario").setVisible(true);
        this.dispose();
    }//GEN-LAST:event_vetButtonActionPerformed

    private void adminButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminButtonActionPerformed
        new LoginInterface("Administrador").setVisible(true);
        this.dispose();
    }//GEN-LAST:event_adminButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Start().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adminButton;
    private javax.swing.JPanel cardCOntent;
    private javax.swing.JButton clientButton;
    private javax.swing.JLabel imgBackground;
    private javax.swing.JButton vetButton;
    private javax.swing.JLabel vetTitle;
    // End of variables declaration//GEN-END:variables
}
