/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

public class AdminInterface extends javax.swing.JFrame {

    public AdminInterface() {
        initComponents();
        centreWindow();
    }

    private void centreWindow() {
        Dimension dimension = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (int) ((dimension.getWidth() - this.getWidth()) / 2);
        int y = (int) ((dimension.getHeight() - this.getHeight()) / 2);
        this.setLocation(x, y - 25);
    }
    File historia;

    public void save(DefaultTableModel model) {


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AgendaAdmin = new javax.swing.JFrame();
        cardcontent = new javax.swing.JPanel();
        showDataPanel = new javax.swing.JScrollPane();
        dataTable = new javax.swing.JTable();
        title = new javax.swing.JPanel();
        saveButton = new javax.swing.JButton();
        agendTItle = new javax.swing.JLabel();
        selectButton = new javax.swing.JButton();
        modifyQuoteButton = new javax.swing.JButton();
        cancelQuoteButton = new javax.swing.JButton();
        asignQuoteButton = new javax.swing.JButton();
        cardContent = new javax.swing.JPanel();
        adminCardTitle = new javax.swing.JPanel();
        adminTitle = new javax.swing.JLabel();
        consultQuoteButton = new javax.swing.JButton();

        AgendaAdmin.setTitle("Agenda de Citas");
        AgendaAdmin.setLocation(new java.awt.Point(150, 100));
        AgendaAdmin.setSize(new java.awt.Dimension(722, 387));

        cardcontent.setPreferredSize(new java.awt.Dimension(723, 382));

        dataTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Fecha Consulta", "Cedula", "Nombre del Perro", "Servicio", "Hora"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        showDataPanel.setViewportView(dataTable);

        title.setBackground(new java.awt.Color(8, 156, 255));

        saveButton.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        saveButton.setText("Guardar ");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });
        title.add(saveButton);

        agendTItle.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        agendTItle.setText("Agenda");
        title.add(agendTItle);

        selectButton.setBackground(new java.awt.Color(8, 156, 255));
        selectButton.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        selectButton.setText("Seleccionar");
        selectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectButtonActionPerformed(evt);
            }
        });

        modifyQuoteButton.setBackground(new java.awt.Color(8, 156, 255));
        modifyQuoteButton.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        modifyQuoteButton.setText("Modificar Cita");
        modifyQuoteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyQuoteButtonActionPerformed(evt);
            }
        });

        cancelQuoteButton.setBackground(new java.awt.Color(8, 156, 255));
        cancelQuoteButton.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        cancelQuoteButton.setText("Eliminar Cita");
        cancelQuoteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelQuoteButtonActionPerformed(evt);
            }
        });

        asignQuoteButton.setBackground(new java.awt.Color(8, 156, 255));
        asignQuoteButton.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        asignQuoteButton.setText("Asignar Cita");
        asignQuoteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asignQuoteButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cardcontentLayout = new javax.swing.GroupLayout(cardcontent);
        cardcontent.setLayout(cardcontentLayout);
        cardcontentLayout.setHorizontalGroup(
            cardcontentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(cardcontentLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(showDataPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
            .addGroup(cardcontentLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(selectButton, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(modifyQuoteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(cancelQuoteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(asignQuoteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        cardcontentLayout.setVerticalGroup(
            cardcontentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cardcontentLayout.createSequentialGroup()
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(showDataPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cardcontentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(cardcontentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(selectButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(cardcontentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cancelQuoteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(modifyQuoteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(asignQuoteButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout AgendaAdminLayout = new javax.swing.GroupLayout(AgendaAdmin.getContentPane());
        AgendaAdmin.getContentPane().setLayout(AgendaAdminLayout);
        AgendaAdminLayout.setHorizontalGroup(
            AgendaAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cardcontent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        AgendaAdminLayout.setVerticalGroup(
            AgendaAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cardcontent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cardContent.setBackground(new java.awt.Color(255, 255, 255));
        cardContent.setPreferredSize(new java.awt.Dimension(650, 440));

        adminCardTitle.setBackground(new java.awt.Color(8, 156, 255));

        adminTitle.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        adminTitle.setText("ADMINISTRADOR");
        adminCardTitle.add(adminTitle);

        consultQuoteButton.setBackground(new java.awt.Color(8, 156, 255));
        consultQuoteButton.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        consultQuoteButton.setText("Consultar Cita ");
        consultQuoteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultQuoteButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cardContentLayout = new javax.swing.GroupLayout(cardContent);
        cardContent.setLayout(cardContentLayout);
        cardContentLayout.setHorizontalGroup(
            cardContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(adminCardTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
            .addGroup(cardContentLayout.createSequentialGroup()
                .addGap(258, 258, 258)
                .addComponent(consultQuoteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        cardContentLayout.setVerticalGroup(
            cardContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardContentLayout.createSequentialGroup()
                .addComponent(adminCardTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(155, 155, 155)
                .addComponent(consultQuoteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 241, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(cardContent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 502, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(cardContent, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void consultQuoteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultQuoteButtonActionPerformed
        AgendaAdmin.setVisible(true);
        File Adminfile = new File("C:\\user\\AgendaAdmin.txt");
        if (Adminfile.exists()) {
            DefaultTableModel model = (DefaultTableModel) dataTable.getModel();
            try (Scanner sc = new Scanner(Adminfile)) {
                while (sc.hasNextLine()) {
                    String linea = sc.nextLine();
                    String data[] = linea.split(",");
                    model.addRow(new Object[]{data[0], data[1], data[2], data[3], data[4]});
                }
            } catch (FileNotFoundException ex) {
                Logger.getLogger(VetInterface.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_consultQuoteButtonActionPerformed

    private void asignQuoteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asignQuoteButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_asignQuoteButtonActionPerformed

    private void selectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectButtonActionPerformed
        DefaultTableModel model = (DefaultTableModel) dataTable.getModel();
        int selected = dataTable.getSelectedRow();
        if (selected > -1) {
            
        }
    }//GEN-LAST:event_selectButtonActionPerformed

    private void modifyQuoteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyQuoteButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modifyQuoteButtonActionPerformed

    private void cancelQuoteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelQuoteButtonActionPerformed
        DefaultTableModel model = (DefaultTableModel) dataTable.getModel();
        int selecteRow = dataTable.getSelectedRow();
        if (selecteRow != -1) {
            model.removeRow(selecteRow);

        }
    }//GEN-LAST:event_cancelQuoteButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        DefaultTableModel model = (DefaultTableModel) dataTable.getModel();
        save(model);
    }//GEN-LAST:event_saveButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame AgendaAdmin;
    private javax.swing.JPanel adminCardTitle;
    private javax.swing.JLabel adminTitle;
    private javax.swing.JLabel agendTItle;
    private javax.swing.JButton asignQuoteButton;
    private javax.swing.JButton cancelQuoteButton;
    private javax.swing.JPanel cardContent;
    private javax.swing.JPanel cardcontent;
    private javax.swing.JButton consultQuoteButton;
    private javax.swing.JTable dataTable;
    private javax.swing.JButton modifyQuoteButton;
    private javax.swing.JButton saveButton;
    private javax.swing.JButton selectButton;
    private javax.swing.JScrollPane showDataPanel;
    private javax.swing.JPanel title;
    // End of variables declaration//GEN-END:variables


