/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Login.Start;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.text.DateFormat;
import java.time.LocalDate;
import java.util.Calendar;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class AdminInterface extends javax.swing.JFrame {

    public AdminInterface() {
        initComponents();
        centreWindow();
    }

    private void centreWindow() {
        Dimension dimension = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (int) ((dimension.getWidth() - this.getWidth()) / 2);
        int y = (int) ((dimension.getHeight() - this.getHeight()) / 2);
        this.setLocation(x, y - 25);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AgendaAdmin = new javax.swing.JFrame();
        cardcontent = new javax.swing.JPanel();
        showDataPanel = new javax.swing.JScrollPane();
        dataTable = new javax.swing.JTable();
        title = new javax.swing.JPanel();
        agendTItle = new javax.swing.JLabel();
        cancelQuoteButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        AsignQuotes = new javax.swing.JFrame();
        content = new javax.swing.JPanel();
        asignTitle = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        bornDateTitle = new javax.swing.JLabel();
        bornDateCollecter = new com.toedter.calendar.JDateChooser();
        reAsignButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cardContent = new javax.swing.JPanel();
        adminCardTitle = new javax.swing.JPanel();
        adminTitle = new javax.swing.JLabel();
        consultQuoteButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        buscar = new javax.swing.JTextField();
        asignQuoteButton = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        AgendaAdmin.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        AgendaAdmin.setTitle("Agenda de Citas");
        AgendaAdmin.setLocation(new java.awt.Point(150, 100));
        AgendaAdmin.setResizable(false);
        AgendaAdmin.setSize(new java.awt.Dimension(735, 430));

        cardcontent.setPreferredSize(new java.awt.Dimension(723, 382));

        dataTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Fecha Consulta", "Cedula", "Nombre del Perro", "Servicio", "Hora", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, false, false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        showDataPanel.setViewportView(dataTable);
        if (dataTable.getColumnModel().getColumnCount() > 0) {
            dataTable.getColumnModel().getColumn(0).setResizable(false);
            dataTable.getColumnModel().getColumn(1).setResizable(false);
            dataTable.getColumnModel().getColumn(2).setResizable(false);
            dataTable.getColumnModel().getColumn(3).setResizable(false);
            dataTable.getColumnModel().getColumn(4).setResizable(false);
            dataTable.getColumnModel().getColumn(5).setResizable(false);
        }

        title.setBackground(new java.awt.Color(8, 156, 255));

        agendTItle.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        agendTItle.setText("Agenda");
        title.add(agendTItle);

        cancelQuoteButton.setBackground(new java.awt.Color(8, 156, 255));
        cancelQuoteButton.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        cancelQuoteButton.setText("Eliminar Cita");
        cancelQuoteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelQuoteButtonActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(8, 156, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cardcontentLayout = new javax.swing.GroupLayout(cardcontent);
        cardcontent.setLayout(cardcontentLayout);
        cardcontentLayout.setHorizontalGroup(
            cardcontentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(cardcontentLayout.createSequentialGroup()
                .addGroup(cardcontentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cardcontentLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(showDataPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(cardcontentLayout.createSequentialGroup()
                        .addGap(229, 229, 229)
                        .addComponent(cancelQuoteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        cardcontentLayout.setVerticalGroup(
            cardcontentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cardcontentLayout.createSequentialGroup()
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(showDataPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(cardcontentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cancelQuoteButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout AgendaAdminLayout = new javax.swing.GroupLayout(AgendaAdmin.getContentPane());
        AgendaAdmin.getContentPane().setLayout(AgendaAdminLayout);
        AgendaAdminLayout.setHorizontalGroup(
            AgendaAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cardcontent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        AgendaAdminLayout.setVerticalGroup(
            AgendaAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cardcontent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        AsignQuotes.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        AsignQuotes.setTitle("Asignación de Citas");
        AsignQuotes.setMinimumSize(new java.awt.Dimension(360, 400));
        AsignQuotes.setPreferredSize(new java.awt.Dimension(517, 430));
        AsignQuotes.setResizable(false);
        AsignQuotes.setSize(new java.awt.Dimension(530, 455));

        content.setBackground(new java.awt.Color(255, 255, 255));

        asignTitle.setBackground(new java.awt.Color(8, 156, 255));

        jLabel4.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel4.setText("Asignar Cita");
        asignTitle.add(jLabel4);

        bornDateTitle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bornDateTitle.setText("Fecha de Consulta:");

        reAsignButton.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        reAsignButton.setText("Asignar");
        reAsignButton.setEnabled(false);
        reAsignButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reAsignButtonActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cedula", "Nombre", "Servicio", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(0).setResizable(false);
            jTable2.getColumnModel().getColumn(1).setResizable(false);
            jTable2.getColumnModel().getColumn(2).setResizable(false);
            jTable2.getColumnModel().getColumn(3).setResizable(false);
        }

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Hora:");

        jTextField1.setEditable(false);

        jButton2.setText("Asignar Hora");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel6.setText("El veterinario atiende los sabados y domingos de 08:00 am - 01:00 pm y");

        jLabel7.setText("de 02:00 pm - 06:00 pm");

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(asignTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(contentLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contentLayout.createSequentialGroup()
                        .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(contentLayout.createSequentialGroup()
                                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(contentLayout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(bornDateTitle))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton2)
                                    .addComponent(bornDateCollecter, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(31, 31, 31)
                                .addComponent(reAsignButton, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(32, Short.MAX_VALUE))
                    .addGroup(contentLayout.createSequentialGroup()
                        .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentLayout.createSequentialGroup()
                .addComponent(asignTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contentLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(bornDateTitle)
                            .addComponent(bornDateCollecter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contentLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(reAsignButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)))
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout AsignQuotesLayout = new javax.swing.GroupLayout(AsignQuotes.getContentPane());
        AsignQuotes.getContentPane().setLayout(AsignQuotesLayout);
        AsignQuotesLayout.setHorizontalGroup(
            AsignQuotesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        AsignQuotesLayout.setVerticalGroup(
            AsignQuotesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Administrador");
        setResizable(false);

        cardContent.setBackground(new java.awt.Color(255, 255, 255));
        cardContent.setPreferredSize(new java.awt.Dimension(650, 440));

        adminCardTitle.setBackground(new java.awt.Color(8, 156, 255));

        adminTitle.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        adminTitle.setText("ADMINISTRADOR");
        adminCardTitle.add(adminTitle);

        consultQuoteButton.setBackground(new java.awt.Color(8, 156, 255));
        consultQuoteButton.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        consultQuoteButton.setText("Consultar agenda");
        consultQuoteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultQuoteButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Facturación de un cliente");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Fecha de Consulta", "Cedula", "Servicio", "Costo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jTextField2.setEditable(false);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Total en caja:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Cedula:");

        buscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                buscarKeyReleased(evt);
            }
        });

        asignQuoteButton.setBackground(new java.awt.Color(8, 156, 255));
        asignQuoteButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        asignQuoteButton.setText("Asignar Cita");
        asignQuoteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asignQuoteButtonActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(8, 156, 255));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setText("Volver");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cardContentLayout = new javax.swing.GroupLayout(cardContent);
        cardContent.setLayout(cardContentLayout);
        cardContentLayout.setHorizontalGroup(
            cardContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(adminCardTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(cardContentLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(cardContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cardContentLayout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addGap(119, 119, 119)
                        .addComponent(jLabel1))
                    .addGroup(cardContentLayout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addGroup(cardContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(cardContentLayout.createSequentialGroup()
                                .addComponent(buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, cardContentLayout.createSequentialGroup()
                                .addComponent(consultQuoteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(asignQuoteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 582, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        cardContentLayout.setVerticalGroup(
            cardContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardContentLayout.createSequentialGroup()
                .addComponent(adminCardTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(cardContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButton3))
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(cardContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(cardContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(consultQuoteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(asignQuoteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(cardContent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 502, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(cardContent, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void consultQuoteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultQuoteButtonActionPerformed
        AgendaAdmin.setVisible(true);
        File Adminfile = new File("C:\\user\\AgendaAdmin.txt");
        if (Adminfile.exists()) {
            DefaultTableModel model = (DefaultTableModel) dataTable.getModel();
            try (Scanner sc = new Scanner(Adminfile)) {
                while (sc.hasNextLine()) {
                    String linea = sc.nextLine();
                    String data[] = linea.split(",");
                    model.addRow(new Object[]{data[0], data[1], data[2], data[3], data[4], data[5]});
                }
                sc.close();
            } catch (FileNotFoundException ex) {
                Logger.getLogger(VetInterface.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_consultQuoteButtonActionPerformed

    private void cancelQuoteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelQuoteButtonActionPerformed
        DefaultTableModel model = (DefaultTableModel) dataTable.getModel();
        int selecteRow = dataTable.getSelectedRow();
        if (selecteRow != -1) {
            model.removeRow(selecteRow);
        } else {
            mensaje("Debe seleccionar una cita");
        }
    }//GEN-LAST:event_cancelQuoteButtonActionPerformed

    private void buscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buscarKeyReleased
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);//Borro los registros
        int total = 0;
        int costo = 0;
        if (Esnumero(buscar.getText()) && !buscar.getText().isEmpty()) {//Reviso que ingrese un numero o que la cadena no este vacia
            File archivo = new File("C:\\user\\AgendaAdmin.txt");
            if (archivo.exists()) {
                try (Scanner sc = new Scanner(archivo)) {//Abro el archivo
                    while (sc.hasNextLine()) {//mientras halla una siguiente linea
                        String linea = sc.nextLine();
                        String data[] = linea.split(",");
                        String fecha = data[0];
                        String cedula = data[1];
                        String nombrePerro = data[2];
                        String servicio = data[3];
                        switch (servicio) {
                            case "Consulta":
                                costo = 60000;
                                break;
                            case "Control":
                                costo = 10000;
                                break;
                            case "Desparasitación":
                                costo = 40000;
                                break;
                            case "Vacunación":
                                costo = 35000;
                                break;
                            case "Guarderia":
                                costo = 35000;
                                break;
                            case "Radiologia":
                                costo = 100000;
                                break;
                            case "Baño":
                                costo = 25000;
                                break;
                        }
                        String estado = data[5];
                        if (cedula.equals(buscar.getText()) && estado.equals("Finalizada")) {//si encuentro coincidencias, muestra los datos en la tabla
                            model.addRow(new Object[]{fecha, cedula, nombrePerro, servicio, costo});//Muestro los datos de esa cedula
                            total += costo;
                        }
                    }
                    sc.close();
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(AdminInterface.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        } else {
            model.setRowCount(0);//Borro otra vez los registros
        }
        jTextField2.setText(String.valueOf(total));
    }//GEN-LAST:event_buscarKeyReleased
    //Valido que la cedula que ingresan sea numerico
    private boolean Esnumero(String cadena) {
        try {
            Integer.parseInt(cadena);
            return true;
        } catch (NumberFormatException e) {
            return false;
        }
    }

    private void reAsignButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reAsignButtonActionPerformed
        int selected = jTable2.getSelectedRow();
        if (selected > -1 && !jTextField1.getText().equals("")) {
            //Datos para crear el archivo de Clientes
            String sDir = "C:\\user"; // direccion
            File f = new File(sDir); // instancia de la carpeta
            String ruta = "C:\\user"; // ruta para el archivo
            String fileName = "AgendaAdmin.txt"; // nombre
            File agenda = new File(ruta, fileName); // instancia el archivo

            if (!agenda.exists()) {//Reviso que el archivo no exista
                try {
                    //mira si el archivo existe o no
                    f.mkdir();
                    agenda.createNewFile();//Creo el archivo
                } catch (IOException ex) {
                    Logger.getLogger(ClientInterface.class.getName()).log(Level.SEVERE, null, ex);
                }

            }

            DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
            //SACAR LA INFORMACION DE TEXTFIELD
            String ced = (String) model.getValueAt(0, 0);
            String nombre = (String) model.getValueAt(0, 1);
            String servicio = (String) model.getValueAt(0, 2);
            String date = DateFormat.getDateInstance().format(bornDateCollecter.getDate());
            String estado = "Asignada";
            String hora = jTextField1.getText();
            Guardar();

            //Escribo la informacion en el archivo
            try (FileWriter fw = new FileWriter(agenda.getAbsolutePath(), true)) {
                BufferedWriter bw = new BufferedWriter(fw);//Creo el buffered
                if (!CitaRepetida(agenda, ced, nombre)) {
                    bw.write(date + "," + ced + "," + nombre + "," + servicio + "," + hora + "," + estado);
                    bw.newLine();
                }
                bw.flush();
                bw.close();
                fw.close();
            } catch (Exception e) {
                Logger.getLogger(ClientInterface.class.getName()).log(Level.SEVERE, null, e);
            }
        }
        jTextField1.setText("");
    }//GEN-LAST:event_reAsignButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        DefaultTableModel model = (DefaultTableModel) dataTable.getModel();
        String sDir = "C:\\user"; // direccion
        File f = new File(sDir); // instancia de la carpeta
        String ruta = "C:\\user"; // ruta para el archivo
        String fileName = "AgendaAdmin.txt"; // nombre
        File Adminfile = new File(ruta, fileName);
        if (!Adminfile.exists()) {
            f.mkdir();
            try {
                Adminfile.createNewFile();
            } catch (IOException ex) {
                Logger.getLogger(AdminInterface.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        try (FileWriter fw = new FileWriter(Adminfile.getAbsoluteFile())) {
            BufferedWriter bw = new BufferedWriter(fw);
            for (int i = 0; i < model.getRowCount(); i++) {
                bw.write((String) model.getValueAt(i, 0) + "," + (String) model.getValueAt(i, 1) + "," + (String) model.getValueAt(i, 2) + "," + (String) model.getValueAt(i, 3) + "," + (String) model.getValueAt(i, 4));
                bw.newLine();
            }
            bw.flush();
            bw.close();
            fw.close();
        } catch (IOException ex) {
            Logger.getLogger(AdminInterface.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int selected = jTable2.getSelectedRow();
        if (selected > -1) {
            int Dia = 0, DiaActual = 0;
            String nombreDia, date = null;
            boolean pass = true;
            try {
                Dia = bornDateCollecter.getCalendar().get(Calendar.DAY_OF_MONTH);
                date = DateFormat.getDateInstance().format(bornDateCollecter.getDate());
                DiaActual = LocalDate.now().getDayOfMonth();
                pass = true;
            } catch (Exception e) {
                mensaje("Verifique si coloco una fecha");
                pass = false;
            }
            if (pass) {
                if (Dia > DiaActual) {
                    nombreDia = String.valueOf(bornDateCollecter.getDate()).substring(0, 3);
                    if (nombreDia.equals("Sat") || nombreDia.equals("Sun")) {//Si el dia es sabado o domingo el veterinario no atiende esos 2 dias
                        mensaje("El Veterinario no atiende los dias sabados ni domingos");
                    } else {
                        String h = AsignarHora(date, "08", "00", "am", selected);
                        if (!h.equals("") && !h.equals(null)) {
                            jTextField1.setText(h);
                            reAsignButton.setEnabled(true);
                        } else if (h.equals("")) {
                            mensaje("No hay horario disponible para ese dia, ingrese otro dia");
                            reAsignButton.setEnabled(false);
                        } else {
                            jTextField1.setText("No necesita");
                        }
                    }
                } else {
                    mensaje("Tiene que ingresar un dia mayor al actual");
                }
            }
        } else {
            mensaje("Tiene que seleccionar una cita");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void asignQuoteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asignQuoteButtonActionPerformed
        AsignQuotes.setVisible(true);
        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
        File cita = new File("C:\\user\\Citas.txt");
        if (cita.exists()) {
            try (Scanner sc = new Scanner(cita)) {
                while (sc.hasNextLine()) {
                    String linea = sc.nextLine();
                    String datos[] = linea.split(",");
                    String cedula = datos[0];
                    String nombre = datos[1];
                    String servicio = datos[2];
                    String estado = datos[3];
                    if (!estado.equals("Cancelada")) {
                        model.addRow(new Object[]{cedula, nombre, servicio, estado});
                    }
                }
                sc.close();
            } catch (FileNotFoundException ex) {
                Logger.getLogger(AdminInterface.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_asignQuoteButtonActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.dispose();
        new Start().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed
    private boolean CitaRepetida(File archivo, String cedula, String nombre) {
        if (archivo.exists()) {
            try (Scanner sc = new Scanner(archivo)) {
                while (sc.hasNextLine()) {
                    String linea = sc.nextLine();
                    String data[] = linea.split(",");
                    if (data[1].equals(cedula) && data[2].equals(nombre)) {
                        return true;
                    }
                }
                sc.close();
                return false;
            } catch (FileNotFoundException ex) {
                Logger.getLogger(ClientInterface.class.getName()).log(Level.SEVERE, null, ex);
                return false;
            }
        }
        return false;
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame AgendaAdmin;
    private javax.swing.JFrame AsignQuotes;
    private javax.swing.JPanel adminCardTitle;
    private javax.swing.JLabel adminTitle;
    private javax.swing.JLabel agendTItle;
    private javax.swing.JButton asignQuoteButton;
    private javax.swing.JPanel asignTitle;
    private com.toedter.calendar.JDateChooser bornDateCollecter;
    private javax.swing.JLabel bornDateTitle;
    private javax.swing.JTextField buscar;
    private javax.swing.JButton cancelQuoteButton;
    private javax.swing.JPanel cardContent;
    private javax.swing.JPanel cardcontent;
    private javax.swing.JButton consultQuoteButton;
    private javax.swing.JPanel content;
    private javax.swing.JTable dataTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JButton reAsignButton;
    private javax.swing.JScrollPane showDataPanel;
    private javax.swing.JPanel title;
    // End of variables declaration//GEN-END:variables

    //Guardo en el archivo citas
    private void Guardar() {
        int selected = jTable2.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
        model.removeRow(selected);
        //Creo las variables para el archivo agenda
        String direccion = "C:\\user";
        File f = new File(direccion);
        String dir = "C:\\user";
        String nameFile = "Citas.txt";
        File cita = new File(dir, nameFile);

        //Reviso que no exista el archivo cita para crearlo
        if (!cita.exists()) {
            try {
                f.mkdir();
                cita.createNewFile();
            } catch (IOException ex) {
                Logger.getLogger(AdminInterface.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

        try (FileWriter fw = new FileWriter(cita.getAbsoluteFile())) {
            BufferedWriter bw = new BufferedWriter(fw);
            for (int i = 0; i < model.getRowCount(); i++) {
                bw.write(model.getValueAt(i, 0) + "," + model.getValueAt(i, 1) + "," + model.getValueAt(i, 2) + "," + "Solicitada");
                bw.newLine();
            }
            bw.flush();
            bw.close();
            fw.close();
        } catch (Exception e) {
            Logger.getLogger(ClientInterface.class.getName()).log(Level.SEVERE, null, e);
        }
    }

    private String AsignarHora(String fecha, String hora, String minutos, String siglas, int selected) {
        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
        File file = new File("C:\\user\\AgendaAdmin.txt");
        if (file.exists()) {
            try (Scanner sc = new Scanner(file)) {
                while (sc.hasNextLine()) {
                    String linea = sc.nextLine();
                    String datos[] = linea.split(",");
                    String date = datos[0];
                    String hour = datos[4];
                    if (date.equals(fecha)) {
                        if (hour.equals(hora + ":" + minutos + " " + siglas)) {
                            if (Integer.parseInt(hora) + 1 < 10) {
                                hora = "0" + String.valueOf(Integer.parseInt(hora) + 1);
                            } else {
                                hora = String.valueOf(Integer.parseInt(hora) + 1);
                            }
                            if (Integer.parseInt(hora) >= 12) {
                                siglas = "pm";
                            }
                            if (Integer.parseInt(hora) == 13) {
                                hora = String.valueOf(Integer.parseInt(hora) + 1);
                            }
                            if (Integer.parseInt(hora) == 18) {
                                return "";
                            }
                        }
                    }
                }
                sc.close();
            } catch (FileNotFoundException ex) {
                Logger.getLogger(AdminInterface.class.getName()).log(Level.SEVERE, null, ex);
            }
            if (model.getValueAt(selected, 2).equals("Baño") || model.getValueAt(selected, 2).equals("Guarderia")) {
                return null;
            }
        }
        return hora + ":" + minutos + " " + siglas;
    }

    private void mensaje(String cadena) {
        try {
            JOptionPane.showMessageDialog(null, cadena);
        } catch (Exception e) {
        }
    }

}
