/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author juanq
 */
public class ClientInterface extends javax.swing.JFrame {

    /**
     * Creates new form clientInterface
     */
    public ClientInterface() {
        initComponents();
        centreWindow(); 
    }

    private void centreWindow() {
        Dimension dimension = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (int) ((dimension.getWidth() - this.getWidth()) / 2);
        int y = (int) ((dimension.getHeight() - this.getHeight()) / 2);
        this.setLocation(x, y - 25);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        content = new javax.swing.JPanel();
        reg_title = new javax.swing.JLabel();
        ccOnwer_title = new javax.swing.JLabel();
        petName_title = new javax.swing.JLabel();
        petRace_title = new javax.swing.JLabel();
        petColor_title = new javax.swing.JLabel();
        bornDate_title = new javax.swing.JLabel();
        ccOwnerTextField = new javax.swing.JTextField();
        petNameTextField = new javax.swing.JTextField();
        petColorTextField = new javax.swing.JTextField();
        petRaceTextField = new javax.swing.JTextField();
        bornDateTextField = new javax.swing.JTextField();
        requestQuoteButton = new javax.swing.JButton();
        modifyQuoteButton = new javax.swing.JButton();
        cancelQuoteButton = new javax.swing.JButton();
        registryButton = new javax.swing.JButton();
        main_tittle = new javax.swing.JPanel();
        tittle = new javax.swing.JLabel();
        showName = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(650, 440));

        content.setBackground(new java.awt.Color(255, 255, 255));
        content.setPreferredSize(new java.awt.Dimension(650, 440));

        reg_title.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        reg_title.setText("Registro");

        ccOnwer_title.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        ccOnwer_title.setText("Cédula del dueño");

        petName_title.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        petName_title.setText("Nombre del perro");

        petRace_title.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        petRace_title.setText("Raza");

        petColor_title.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        petColor_title.setText("Color ");

        bornDate_title.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        bornDate_title.setText("Fecha Nacimiento");

        ccOwnerTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ccOwnerTextFieldActionPerformed(evt);
            }
        });

        petNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                petNameTextFieldActionPerformed(evt);
            }
        });

        petColorTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                petColorTextFieldActionPerformed(evt);
            }
        });

        petRaceTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                petRaceTextFieldActionPerformed(evt);
            }
        });

        bornDateTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bornDateTextFieldActionPerformed(evt);
            }
        });

        requestQuoteButton.setBackground(new java.awt.Color(8, 156, 255));
        requestQuoteButton.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        requestQuoteButton.setText("Solicitar cita");
        requestQuoteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestQuoteButtonActionPerformed(evt);
            }
        });

        modifyQuoteButton.setBackground(new java.awt.Color(8, 156, 255));
        modifyQuoteButton.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        modifyQuoteButton.setText("Modificar cita");
        modifyQuoteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyQuoteButtonActionPerformed(evt);
            }
        });

        cancelQuoteButton.setBackground(new java.awt.Color(8, 156, 255));
        cancelQuoteButton.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        cancelQuoteButton.setText("Cancelar cita");

        registryButton.setBackground(new java.awt.Color(8, 156, 255));
        registryButton.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        registryButton.setText("Registrar");
        registryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registryButtonActionPerformed(evt);
            }
        });

        main_tittle.setBackground(new java.awt.Color(8, 156, 255));

        tittle.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        tittle.setText("BIENVENIDO");
        main_tittle.add(tittle);

        showName.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        main_tittle.add(showName);

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main_tittle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(contentLayout.createSequentialGroup()
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contentLayout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(petColor_title)
                        .addGap(159, 159, 159)
                        .addComponent(petRace_title))
                    .addGroup(contentLayout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(bornDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(modifyQuoteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(contentLayout.createSequentialGroup()
                                .addGap(159, 159, 159)
                                .addComponent(registryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(contentLayout.createSequentialGroup()
                                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(contentLayout.createSequentialGroup()
                                        .addGap(50, 50, 50)
                                        .addComponent(ccOnwer_title)
                                        .addGap(83, 83, 83)
                                        .addComponent(petName_title))
                                    .addGroup(contentLayout.createSequentialGroup()
                                        .addGap(167, 167, 167)
                                        .addComponent(reg_title, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(87, 87, 87)
                                .addComponent(requestQuoteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, contentLayout.createSequentialGroup()
                            .addGap(144, 144, 144)
                            .addComponent(bornDate_title)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cancelQuoteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(contentLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(petColorTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                            .addComponent(ccOwnerTextField))
                        .addGap(46, 46, 46)
                        .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(petNameTextField)
                            .addComponent(petRaceTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE))))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentLayout.createSequentialGroup()
                .addComponent(main_tittle, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contentLayout.createSequentialGroup()
                        .addComponent(reg_title)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ccOnwer_title)
                            .addComponent(petName_title))
                        .addGap(19, 19, 19)
                        .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ccOwnerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(petNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(petColor_title)
                            .addComponent(petRace_title))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(petColorTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                            .addComponent(petRaceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(bornDate_title)
                        .addGap(14, 14, 14)
                        .addComponent(bornDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(registryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(contentLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(requestQuoteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(modifyQuoteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cancelQuoteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, 648, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ccOwnerTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ccOwnerTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ccOwnerTextFieldActionPerformed

    private void petNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_petNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_petNameTextFieldActionPerformed

    private void petColorTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_petColorTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_petColorTextFieldActionPerformed

    private void petRaceTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_petRaceTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_petRaceTextFieldActionPerformed

    private void bornDateTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bornDateTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bornDateTextFieldActionPerformed

    private void registryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registryButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registryButtonActionPerformed

    private void requestQuoteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestQuoteButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_requestQuoteButtonActionPerformed

    private void modifyQuoteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyQuoteButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modifyQuoteButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bornDateTextField;
    private javax.swing.JLabel bornDate_title;
    private javax.swing.JButton cancelQuoteButton;
    private javax.swing.JLabel ccOnwer_title;
    private javax.swing.JTextField ccOwnerTextField;
    private javax.swing.JPanel content;
    private javax.swing.JPanel main_tittle;
    private javax.swing.JButton modifyQuoteButton;
    private javax.swing.JTextField petColorTextField;
    private javax.swing.JLabel petColor_title;
    private javax.swing.JTextField petNameTextField;
    private javax.swing.JLabel petName_title;
    private javax.swing.JTextField petRaceTextField;
    private javax.swing.JLabel petRace_title;
    private javax.swing.JLabel reg_title;
    private javax.swing.JButton registryButton;
    private javax.swing.JButton requestQuoteButton;
    private javax.swing.JLabel showName;
    private javax.swing.JLabel tittle;
    // End of variables declaration//GEN-END:variables
}
