package Interfaces;

import Login.Start;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class VetInterface extends javax.swing.JFrame {

    /**
     * Creates new form vetInterface
     */
    public VetInterface() {
        initComponents();
        centreWindow();
    }

    private void centreWindow() {
        Dimension dimension = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (int) ((dimension.getWidth() - this.getWidth()) / 2);
        int y = (int) ((dimension.getHeight() - this.getHeight()) / 2);
        this.setLocation(x, y - 25);
    }
    File historia;
    File agenda;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Agenda = new javax.swing.JFrame();
        cardcontent = new javax.swing.JPanel();
        title = new javax.swing.JPanel();
        agendTItle = new javax.swing.JLabel();
        showDataPanel = new javax.swing.JScrollPane();
        dataTable = new javax.swing.JTable();
        selectButton = new javax.swing.JButton();
        content = new javax.swing.JPanel();
        contenTtitle = new javax.swing.JLabel();
        consultButton = new javax.swing.JButton();
        createHButton = new javax.swing.JButton();
        showScrollPaneP = new javax.swing.JScrollPane();
        preescripcion = new javax.swing.JTextArea();
        presctitle = new javax.swing.JLabel();
        showScrollPane = new javax.swing.JScrollPane();
        diagnostico = new javax.swing.JTextArea();
        diagnosticTitle = new javax.swing.JLabel();
        petNameTitle = new javax.swing.JLabel();
        ccOnwerTitle = new javax.swing.JLabel();
        consultDateTitle = new javax.swing.JLabel();
        dateTextField = new javax.swing.JTextField();
        ccTextField = new javax.swing.JTextField();
        petTextField = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        imgBackground = new javax.swing.JLabel();

        Agenda.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        Agenda.setTitle("Agenda de Citas");
        Agenda.setLocation(new java.awt.Point(150, 100));
        Agenda.setResizable(false);
        Agenda.setSize(new java.awt.Dimension(723, 490));

        title.setBackground(new java.awt.Color(8, 156, 255));

        agendTItle.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        agendTItle.setText("Agenda");
        title.add(agendTItle);

        dataTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Fecha Consulta", "Cedula", "Nombre del Perro", "Servicio", "Hora"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        showDataPanel.setViewportView(dataTable);

        selectButton.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        selectButton.setText("Seleccionar");
        selectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cardcontentLayout = new javax.swing.GroupLayout(cardcontent);
        cardcontent.setLayout(cardcontentLayout);
        cardcontentLayout.setHorizontalGroup(
            cardcontentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(cardcontentLayout.createSequentialGroup()
                .addGroup(cardcontentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cardcontentLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(showDataPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 672, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(cardcontentLayout.createSequentialGroup()
                        .addGap(274, 274, 274)
                        .addComponent(selectButton, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        cardcontentLayout.setVerticalGroup(
            cardcontentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cardcontentLayout.createSequentialGroup()
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(showDataPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(selectButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout AgendaLayout = new javax.swing.GroupLayout(Agenda.getContentPane());
        Agenda.getContentPane().setLayout(AgendaLayout);
        AgendaLayout.setHorizontalGroup(
            AgendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cardcontent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        AgendaLayout.setVerticalGroup(
            AgendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AgendaLayout.createSequentialGroup()
                .addComponent(cardcontent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Veterinario");
        setResizable(false);

        content.setBackground(new java.awt.Color(255, 255, 255));
        content.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        contenTtitle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        contenTtitle.setForeground(new java.awt.Color(255, 255, 255));
        contenTtitle.setText("Historia Clinica");
        content.add(contenTtitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        consultButton.setBackground(new java.awt.Color(8, 156, 255));
        consultButton.setText("Consultar la Agenda");
        consultButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultButtonActionPerformed(evt);
            }
        });
        content.add(consultButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 320, 160, 40));

        createHButton.setBackground(new java.awt.Color(8, 156, 255));
        createHButton.setText("Crear Historia Clinica");
        createHButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createHButtonActionPerformed(evt);
            }
        });
        content.add(createHButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 370, 160, 40));

        preescripcion.setColumns(20);
        preescripcion.setRows(5);
        showScrollPaneP.setViewportView(preescripcion);

        content.add(showScrollPaneP, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, -1, -1));

        presctitle.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        presctitle.setForeground(new java.awt.Color(255, 255, 255));
        presctitle.setText("Preescripción");
        content.add(presctitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, -1, -1));

        diagnostico.setColumns(20);
        diagnostico.setRows(5);
        showScrollPane.setViewportView(diagnostico);

        content.add(showScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, -1));

        diagnosticTitle.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        diagnosticTitle.setForeground(new java.awt.Color(255, 255, 255));
        diagnosticTitle.setText("Diagnostico");
        content.add(diagnosticTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, -1));

        petNameTitle.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        petNameTitle.setForeground(new java.awt.Color(255, 255, 255));
        petNameTitle.setText("Nombre del Perro:");
        content.add(petNameTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        ccOnwerTitle.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ccOnwerTitle.setForeground(new java.awt.Color(255, 255, 255));
        ccOnwerTitle.setText("Cedula del dueño:");
        content.add(ccOnwerTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        consultDateTitle.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        consultDateTitle.setForeground(new java.awt.Color(255, 255, 255));
        consultDateTitle.setText("Fecha de la consulta:");
        content.add(consultDateTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        dateTextField.setEnabled(false);
        content.add(dateTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 120, -1));

        ccTextField.setEnabled(false);
        content.add(ccTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 120, -1));

        petTextField.setEnabled(false);
        content.add(petTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 120, -1));

        jButton3.setBackground(new java.awt.Color(8, 156, 255));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setText("Volver");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        content.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, -1, -1));

        imgBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/data/Imagenes/Veterinario.jpg"))); // NOI18N
        content.add(imgBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void consultButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultButtonActionPerformed
        Agenda.setVisible(true);
        File file = new File("C:\\user\\AgendaAdmin.txt");
        DefaultTableModel model = (DefaultTableModel) dataTable.getModel();
        model.setRowCount(0);
        if (file.exists()) {
            try (Scanner sc = new Scanner(file)) {
                while (sc.hasNextLine()) {
                    String linea = sc.nextLine();
                    String data[] = linea.split(",");
                    if (data[5].equals("Asignada")) {
                        model.addRow(new Object[]{data[0], data[1], data[2], data[3], data[4]});
                    }
                }
            } catch (FileNotFoundException ex) {
               JOptionPane.showMessageDialog(content, "Archivo no encontrado", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_consultButtonActionPerformed

    private void createHButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createHButtonActionPerformed
        String data[] = {dateTextField.getText(), ccTextField.getText(), petTextField.getText(), diagnostico.getText(), preescripcion.getText()};
        if (NoVacia(data)) {
            String sDir = "C:\\user"; // direccion
            File f = new File(sDir); // instancia de la carpeta
            String ruta = "C:\\user"; // ruta para el archivo
            String fileName = "Historias Clinicas.txt"; // nombre
            historia = new File(ruta, fileName); // instancia el archivo

            if (!historia.exists()) {
                f.mkdir();
                try {
                    historia.createNewFile();
                } catch (IOException ex) {
                    JOptionPane.showMessageDialog(content, "Error inesperado", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }

            try (FileWriter fw = new FileWriter(historia.getAbsoluteFile(), true)) {
                BufferedWriter bw = new BufferedWriter(fw);
                bw.write(data[0] + "," + data[1] + "," + data[2] + "," + data[3] + "," + data[4]);
                bw.newLine();
                bw.flush();
                bw.close();
                fw.close();
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(content, "Error inesperado", "Error", JOptionPane.ERROR_MESSAGE);
            }
            CambiarEstadoCita();//al crear la historia clinica, la cita se daria por finalizada
        } else {
            JOptionPane.showMessageDialog(content, "Ningún campo debe estar vacío, vuelva a intentarlo", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_createHButtonActionPerformed

    private void selectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectButtonActionPerformed
        DefaultTableModel model = (DefaultTableModel) dataTable.getModel();
        int selected = dataTable.getSelectedRow();
        if (selected > -1) {
            dateTextField.setText((String) model.getValueAt(selected, 0));
            ccTextField.setText((String) model.getValueAt(selected, 1));
            petTextField.setText((String) model.getValueAt(selected, 2));
            Agenda.dispose();
        } else {
            JOptionPane.showMessageDialog(content, "Debe seleccionar una cita", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_selectButtonActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.dispose();
        new Start().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VetInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VetInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VetInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VetInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VetInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame Agenda;
    private javax.swing.JLabel agendTItle;
    private javax.swing.JPanel cardcontent;
    private javax.swing.JLabel ccOnwerTitle;
    private javax.swing.JTextField ccTextField;
    private javax.swing.JButton consultButton;
    private javax.swing.JLabel consultDateTitle;
    private javax.swing.JLabel contenTtitle;
    private javax.swing.JPanel content;
    private javax.swing.JButton createHButton;
    private javax.swing.JTable dataTable;
    private javax.swing.JTextField dateTextField;
    private javax.swing.JLabel diagnosticTitle;
    private javax.swing.JTextArea diagnostico;
    private javax.swing.JLabel imgBackground;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel petNameTitle;
    private javax.swing.JTextField petTextField;
    private javax.swing.JTextArea preescripcion;
    private javax.swing.JLabel presctitle;
    private javax.swing.JButton selectButton;
    private javax.swing.JScrollPane showDataPanel;
    private javax.swing.JScrollPane showScrollPane;
    private javax.swing.JScrollPane showScrollPaneP;
    private javax.swing.JPanel title;
    // End of variables declaration//GEN-END:variables

    private boolean NoVacia(String[] cadena) {
        boolean novacia = true;
        for (String cad : cadena) {
            if (cad.isEmpty()) {
                novacia = false;
            }
        }
        return novacia;
    }

    private void CambiarEstadoCita() {
        String sDir = "C:\\user"; // Dirección absoluta
        File f = new File(sDir); // Instancia de la carpeta
        String ruta = "C:\\user"; // Ruta relativa del archivo
        String fileName = "Cambios.txt"; // Nombre
        File cambios = new File(ruta, fileName); // Instancia el archivo
        agenda = new File("C:\\user\\AgendaAdmin.txt");

        if (!cambios.exists()) {
            f.mkdir();
            try {
                cambios.createNewFile();
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(content, "Error inesperado", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        if (agenda.exists()) {
            try (FileWriter fw = new FileWriter(cambios.getAbsoluteFile())) {
                BufferedWriter bw = new BufferedWriter(fw);
                Scanner sc = new Scanner(agenda);
                while (sc.hasNextLine()) {
                    String linea = sc.nextLine();
                    String datos[] = linea.split(",");
                    String fecha = datos[0];
                    String ced = datos[1];
                    String nombre = datos[2];
                    String servicio = datos[3];
                    String hora = datos[4];
                    String estado = datos[5];
                    if (ccTextField.getText().equals(ced) && petTextField.getText().equals(nombre)) {
                        estado = "Finalizada";
                    }
                    bw.write(fecha + "," + ced + "," + nombre + "," + servicio + "," + hora + "," + estado);
                    bw.newLine();
                }
                bw.flush();
                bw.close();
                fw.close();
                sc.close();
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(content, "Error inesperado", "Error", JOptionPane.ERROR_MESSAGE);
            }

            //Actualiza la informacion en el archivo de la agenda
            try (FileWriter fw = new FileWriter(agenda.getAbsoluteFile())) {
                BufferedWriter bw = new BufferedWriter(fw);
                Scanner sc = new Scanner(cambios);
                while (sc.hasNextLine()) {
                    String linea = sc.nextLine();
                    String datos[] = linea.split(",");
                    bw.write(datos[0] + "," + datos[1] + "," + datos[2] + "," + datos[3] + "," + datos[4] + "," + datos[5]);
                    bw.newLine();
                }
                bw.flush();
                bw.close();
                fw.close();
                sc.close();
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(content, "Error inesperado", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        cambios.delete();
    }

}
