package Login;

import Interfaces.AdminInterface;
import Interfaces.ClientInterface;
import Interfaces.VetInterface;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

public class LoginInterface extends javax.swing.JFrame {

    private String user;

    public LoginInterface(String user) {
        this.user = user;
        initComponents();
        centreWindow();
    }

    private void centreWindow() {
        Dimension dimension = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (int) ((dimension.getWidth() - this.getWidth()) / 2);
        int y = (int) ((dimension.getHeight() - this.getHeight()) / 2);
        this.setLocation(x, y - 25);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cardContent = new javax.swing.JPanel();
        loginSection = new javax.swing.JPanel();
        login_tittle = new javax.swing.JLabel();
        nameText = new javax.swing.JTextField();
        keyText = new javax.swing.JTextField();
        keyTittle = new javax.swing.JLabel();
        nameTittle = new javax.swing.JLabel();
        singInbutton = new javax.swing.JPanel();
        singIn_title = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(400, 375));
        setResizable(false);

        cardContent.setBackground(new java.awt.Color(255, 255, 255));

        loginSection.setBackground(new java.awt.Color(8, 156, 255));

        login_tittle.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        login_tittle.setText("Login");
        loginSection.add(login_tittle);

        keyTittle.setFont(new java.awt.Font("Roboto", 1, 20)); // NOI18N
        keyTittle.setText("Clave");

        nameTittle.setFont(new java.awt.Font("Roboto", 1, 20)); // NOI18N
        nameTittle.setText("Nombre");

        singInbutton.setBackground(new java.awt.Color(8, 156, 255));
        singInbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                singInbuttonMouseClicked(evt);
            }
        });

        singIn_title.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        singIn_title.setText("Iniciar");
        singInbutton.add(singIn_title);

        javax.swing.GroupLayout cardContentLayout = new javax.swing.GroupLayout(cardContent);
        cardContent.setLayout(cardContentLayout);
        cardContentLayout.setHorizontalGroup(
            cardContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginSection, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(cardContentLayout.createSequentialGroup()
                .addGroup(cardContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cardContentLayout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(nameTittle))
                    .addGroup(cardContentLayout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(keyTittle))
                    .addGroup(cardContentLayout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(singInbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(cardContentLayout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addGroup(cardContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nameText)
                            .addComponent(keyText, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE))))
                .addContainerGap(103, Short.MAX_VALUE))
        );
        cardContentLayout.setVerticalGroup(
            cardContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardContentLayout.createSequentialGroup()
                .addComponent(loginSection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(nameTittle)
                .addGap(22, 22, 22)
                .addComponent(nameText, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(keyTittle)
                .addGap(18, 18, 18)
                .addComponent(keyText, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(singInbutton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cardContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cardContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void singInbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_singInbuttonMouseClicked
        String nombre = nameText.getText();
        int key = Integer.parseInt(keyText.getText());
        if (user.equals("Cliente")) {//Usuario y clave para el modulo cliente
            new ClientInterface().setVisible(true);
            this.dispose();
        } else if (user.equals("Veterinario") && nombre.equals("Edilberto") && key == 1111) {//Usuario y clave para el modulo veterinario
            new VetInterface().setVisible(true);
            this.dispose();
        } else if (user.equals("Administrador") && nombre.equals("Juan") && key == 1234) {//Ususario y clave para el modulo administrador
            new AdminInterface().setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(cardContent,"Usuario o contraseña incorrectos, digite nuevamente","Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_singInbuttonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginInterface(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel cardContent;
    private javax.swing.JTextField keyText;
    private javax.swing.JLabel keyTittle;
    private javax.swing.JPanel loginSection;
    private javax.swing.JLabel login_tittle;
    private javax.swing.JTextField nameText;
    private javax.swing.JLabel nameTittle;
    private javax.swing.JLabel singIn_title;
    private javax.swing.JPanel singInbutton;
    // End of variables declaration//GEN-END:variables
}
